### PR TITLE
Request for Form validation PR Review

### PR DESCRIPTION
**Pull request by flemton**
### Below were the changes implemented

- Added formValidation.js file
- Added Javascript variable
- Added Javascript code to validate Email
- Added Event to check validation on submit click
- Fixed linter errors and formatted HTML
__Any needed corrections and suggestions are welcome__
**Cheers 🥂**

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Newton,
 
 While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
 
 ## Invalid Code Review Request
You have submitted a project, whereby ESLint checks not showing on your Pull Request. Kindly ensure that **all** required linters are properly configured, and checks are passing. Kindly request for another code review when this is done.

**ESLint not showing:**
image
 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by flemton** [comment]
@rloterh Thank you very much for the time taken to review my PR, I am honored 👍 , but I am not sure I understand you sir, ESLint works in my local repo, maybe its not supposed to be part of the checks on the PR? If it is may I know how I will set it correctly for it to appear?
Thanks in advance sir

**Comment by rloterh** [comment]
@flemton 
I suggest you do a clean installation of linters following strictly the step-by-step guide via [this link](https://github.com/microverseinc/linters-config/tree/master/html-css-js).
- Remove all linter config files
- Delete `node_modules` directory
- Do a fresh installation of linters
- Ensure that there are no linter errors.
- Commit and push your changes

I hope this helps..cheers! 😃

**Comment by flemton** [comment]
@rloterh Hello thanks again sir, I did that but my local repo says nothing to commit because there are no changes, would it be okay to show me a screenshot of the ESLint checks in a PR? So I know what to do next?

**Review by Favourezeugwa — APPROVED** [review]
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @flemton, 

I am Favour 👩🏽 , your reviewer for this PR.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

happy

## Highlights 💯 
- No Linter errors ✔️
- Good commit messages ✔️
- Professional Readme file ✔️
- Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
